package service;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class TestConnect {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }
    @Test
    public void baidu() {
        driver.get("https://github.com/");
        driver.manage().window().setSize(new Dimension(1552, 840));
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.linkText("Read the guide")).click();
        vars.put("win786", waitForWindow(2000));
        vars.put("root", driver.getWindowHandle());
        driver.switchTo().window(vars.get("win786").toString());
        driver.switchTo().window(vars.get("root").toString());
        driver.switchTo().window(vars.get("win786").toString());
        driver.findElement(By.linkText("Create a Repository")).click();
        driver.close();
        driver.switchTo().window(vars.get("root").toString());
        driver.findElement(By.cssSelector(".mb-3 .public:nth-child(1) .d-inline-flex > .flex-shrink-0")).click();
        {
            WebElement element = driver.findElement(By.linkText("Code"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.id("js-repo-pjax-container")).click();
        driver.findElement(By.cssSelector(".get-repo-select-menu > .btn")).click();
        driver.findElement(By.linkText("Download ZIP")).click();
    }
}
